### ISSUE TITLE
cache.increment got exception  ValueError: invalid literal for int() with base 10: 'value'

### ISSUE THREAD

**Issue by mouday** [sdispater/cachy#8]
cache.increment('key', 1)

Traceback (most recent call last):
  File "workspace/DataSpider/script/orator-test.py", line 76, in <module>
    cache.increment('key', 1)
  File ".pyenv/versions/py370/lib/python3.7/site-packages/cachy/stores/file_store.py", line 128, in increment
    integer = int(raw['data']) + value
ValueError: invalid literal for int() with base 10: 'value'

**Comment by mjpieters** [comment]
This is similar to errors seen when cachy is not not handling concurrent access from multiple processes, see #22.
